# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(help_text='Name of template file without file extension', max_length=50, verbose_name='Name of template')),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(help_text='Context dictionary', verbose_name='Context for filling in template')),
                ('output_filename', models.CharField(help_text='Including file extension (.pdf)', max_length=50, verbose_name='Name of output PDF file')),
            ],
        ),
    ]
