# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:34
from __future__ import unicode_literals

import apps.tenants.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20170316_1119'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('objects', apps.tenants.models.TenantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', validators=[apps.tenants.models.validate_default_site]),
        ),
    ]
