# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20170317_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.Tenant'),
        ),
    ]
