# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20170321_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'invite', 'verbose_name_plural': 'invites'},
        ),
    ]
