# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_auto_20170327_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Name of the tenant (the agency or company)', max_length=100, unique=True),
        ),
    ]

