# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20170329_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='first_name',
            field=models.CharField(blank=True, help_text='First Name of the user', max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='invite',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name of the user', max_length=30, verbose_name='last name'),
        ),
    ]
