# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_auto_20170510_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created_user',
            field=models.OneToOneField(blank=True, help_text='Which user was created from invite?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_used', to=settings.AUTH_USER_MODEL, verbose_name='created user'),
        ),
        migrations.AddField(
            model_name='invite',
            name='first_clicked',
            field=models.DateTimeField(blank=True, help_text='When was the first time the invitee clicked on the invite?', null=True, verbose_name='first clicked'),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(help_text='Who invited the person?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL, verbose_name='inviter'),
        ),
        migrations.AddField(
            model_name='invite',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the invite created?', verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='invite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(help_text='Email of the invitee', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='first_name',
            field=models.CharField(blank=True, help_text='First Name of the invitee', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name of the invitee', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When did the tenant join?', verbose_name='date joined'),
        ),
    ]
