# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20170622_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='id',
        ),
        migrations.AlterField(
            model_name='invite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
