# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_auto_20170622_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='uuid',
            new_name='id',
        ),
    ]
