# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0010_auto_20170622_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='created_user',
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Which user was created or connected from invite?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_used', to=settings.AUTH_USER_MODEL, verbose_name='connected user'),
        ),
    ]
