# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('object_id', models.CharField(max_length=36)),
                ('content', models.TextField(help_text='The text of the comment', verbose_name='content')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the comment created?', verbose_name='Creation time')),
                ('author', models.ForeignKey(help_text='Who wrote the comment?', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
