# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unneeded_field_to_test_correct_migrations',
            field=models.BooleanField(default=False),
        ),
    ]
