# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0004_remove_user_unneeded_field_to_test_correct_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(help_text='Where is the user registered?', to='tenants.Tenant'),
        ),
    ]
