# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_loggedinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenants',
        ),
    ]
