# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20170329_0831'),
        ('users', '0008_remove_user_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(help_text='Where is the user registered?', through='users.UserTenantRelationship', to='tenants.Tenant'),
        ),
    ]
