# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170408_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertenantrelationship',
            options={'verbose_name': 'employment', 'verbose_name_plural': 'employments'},
        ),
    ]
