# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170510_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='signed_in',
            field=models.DateTimeField(help_text='Is the user signed in?', null=True, verbose_name='Signed in'),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
