# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('delivery_mail_id', models.IntegerField(blank=True, help_text='The ID is saved after correct sending', null=True, verbose_name='Unique mail sender ID')),
                ('delivery_status', models.IntegerField(blank=True, help_text='The Mail sender status', null=True, verbose_name='Status of Mail sender')),
                ('template', models.CharField(help_text='The used text/HTML template - exists as a file', max_length=50, verbose_name='Used Mail template')),
                ('subject', models.CharField(max_length=500)),
                ('context', models.TextField()),
                ('time_queued', models.DateTimeField()),
                ('time_sent', models.DateTimeField()),
                ('time_delivered', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
