# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='time_delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_queued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
