# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20170309_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='context',
            field=models.TextField(help_text='JSON dump of context dictionary used to fill in templates', verbose_name='Data of email context'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='from_address',
            field=models.EmailField(help_text="The 'from' field of the email", max_length=254, verbose_name='Sender email address'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(help_text='Subject line, saved after generating from context', max_length=500, verbose_name='Email Subject line'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_delivered',
            field=models.DateTimeField(blank=True, help_text='This is given by the Mail sender', null=True, verbose_name='Time mail was delivered'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_queued',
            field=models.DateTimeField(blank=True, help_text='This is when send_async.. is called', null=True, verbose_name='Time mail was added to the send queue'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_sent',
            field=models.DateTimeField(blank=True, help_text='This is when mail.send is called', null=True, verbose_name='Time mail was sent'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to_address',
            field=models.EmailField(help_text="The 'to' field of the email", max_length=254, verbose_name='Recipient email address'),
        ),
    ]
