# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20170312_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON dump of context dictionary used to fill in templates', verbose_name='Data of email context'),
        ),
    ]
