# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_auto_20170313_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='time_queued',
        ),
        migrations.AddField(
            model_name='mail',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When was the mail created?', verbose_name='Creation time'),
        ),
        migrations.AddField(
            model_name='mail',
            name='used_backend',
            field=models.CharField(blank=True, help_text='Which email backend was used for sending?', max_length=128, null=True, verbose_name='E-Mail Backend'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_delivered',
            field=models.DateTimeField(blank=True, help_text='Actual delivery time by the email backend', null=True, verbose_name='Delivery time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_sent',
            field=models.DateTimeField(blank=True, help_text='When was the mail send via the backend?', null=True, verbose_name='Sent time'),
        ),
    ]
