# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_mailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='subject_template',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='html_template',
            field=tinymce.models.HTMLField(help_text='Use django template syntax', verbose_name='HTML template (required)'),
        ),
    ]
