# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_auto_20170503_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='template',
        ),
    ]
