# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0011_add_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='template',
            field=models.ForeignKey(default=1, help_text='The used text/HTML template - exists as a file', on_delete=django.db.models.deletion.CASCADE, to='mails.MailTemplate', verbose_name='Used Mail template'),
            preserve_default=False,
        ),
    ]
