# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0012_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='delivery_mail_id',
            field=models.IntegerField(blank=True, editable=False, help_text='The ID is saved after correct sending', null=True, verbose_name='Unique mail sender ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='delivery_status',
            field=models.IntegerField(blank=True, editable=False, help_text='The Mail sender status', null=True, verbose_name='Status of Mail sender'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='template',
            field=models.ForeignKey(help_text='The used template', on_delete=django.db.models.deletion.CASCADE, to='mails.MailTemplate', verbose_name='Used Mail template'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the mail created?', verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_delivered',
            field=models.DateTimeField(blank=True, editable=False, help_text='Actual delivery time by the email backend', null=True, verbose_name='Delivery time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_sent',
            field=models.DateTimeField(blank=True, editable=False, help_text='When was the mail send via the backend?', null=True, verbose_name='Sent time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='used_backend',
            field=models.CharField(blank=True, editable=False, help_text='Which email backend was used for sending?', max_length=128, null=True, verbose_name='E-Mail Backend'),
        ),
    ]
