# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0012_auto_20170503_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When was the mail created?', verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time_sent',
            field=models.DateTimeField(blank=True, editable=False, help_text='When was the mail send via the backend?', null=True, verbose_name='Sent time'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='used_backend',
            field=models.CharField(blank=True, editable=False, help_text='Which email backend was used for sending?', max_length=128, null=True, verbose_name='E-Mail Backend'),
        ),
    ]
