# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0013_auto_20170503_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='delivery_mail_id',
            field=models.IntegerField(blank=True, editable=False, help_text='The ID is saved after correct sending', null=True, verbose_name='Unique mail sender ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='delivery_status',
            field=models.IntegerField(blank=True, editable=False, help_text='The Mail sender status', null=True, verbose_name='Status of Mail sender'),
        ),
    ]
