# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0013_auto_20170503_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(help_text='Template name; a short all-lowercase string', max_length=100, unique=True, verbose_name='Template name'),
        ),
    ]
